cniInstallScript: /cni-install.sh
cniUninstallScript: /cni-uninstall.sh
image: cilium
initScript: /init-container.sh

# Specifies the maximum number of Pods that can be unavailable during the
# update process.
maxUnavailable: 2

# Enables monitor sidecar container for specified event types
monitor:
  enabled: false
  eventTypes: []
